# Generated by Django 4.1.3 on 2022-11-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimplifiedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirection_path', models.CharField(max_length=10)),
                ('url_to_redirect', models.URLField()),
            ],
        ),
    ]
