# Generated by Django 4.1.3 on 2022-12-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplifiedurl',
            name='redirection_path',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
